export const NFTsinDrop = [
  {
    name: "Duck, Duck, Goose!",
    rarity: "common",
    image: "https://arweave.net/hZFwr9SjKg0NQEPLqKtSeDXgEAgmY-X2RfCKCePKZAM?ext=png",
    uri: "https://arweave.net/wu1Vn2r1djRB0_keN_z51klJugdK4cQBED6THLKgVcM",
    magicEdenLink: "https://www.tensor.trade/trade/drip_floor",
    news: [
      { value: "$8.5M", trait_type: "Solana NFT Sales Volume" },
      { value: "158k", trait_type: "Solana NFT # of Sales" },
      { value: "37k", trait_type: "Solana NFT # of Buyers" },
      { value: "$15.77", trait_type: "Price of SOL" },
      { value: "The Goose Sells at Sotheby’s for $6.2M", trait_type: "Headline 1" },
      { value: "Crypto Community Rallies to Support ZachXBT", trait_type: "Headline 2" },
      { value: "SolanaMonkeyBusiness Announces Gen 3 Mint Details", trait_type: "Headline 3" },
      { value: "Mad Lads", trait_type: "Highest Volume 1" },
      { value: "Zero Monke Biz", trait_type: "Highest Volume 2" },
      { value: "Okay Bears", trait_type: "Highest Volume 3" },
    ],
  },
  {
    name: "Duck, Duck, Golden Goose!",
    rarity: "legendary",
    image: "https://arweave.net/QDhWzH4NuJntoPwpiOsGyM0g8skVZzwv-Dc5iDcR-bI?ext=png",
    uri: "https://arweave.net/yz_fh54NEwelviOqQj7zBryA7tqJcDrEh9vOrlRl5mM",
    magicEdenLink: "https://www.tensor.trade/trade/drip_floor",
    news: [
      { value: "$8.5M", trait_type: "Solana NFT Sales Volume" },
      { value: "158k", trait_type: "Solana NFT # of Sales" },
      { value: "37k", trait_type: "Solana NFT # of Buyers" },
      { value: "$15.77", trait_type: "Price of SOL" },
      { value: "The Goose Sells at Sotheby’s for $6.2M", trait_type: "Headline 1" },
      { value: "Crypto Community Rallies to Support ZachXBT", trait_type: "Headline 2" },
      { value: "SolanaMonkeyBusiness Announces Gen 3 Mint Details", trait_type: "Headline 3" },
      { value: "Mad Lads", trait_type: "Highest Volume 1" },
      { value: "Zero Monke Biz", trait_type: "Highest Volume 2" },
      { value: "Okay Bears", trait_type: "Highest Volume 3" },
    ],
  },
];
