export const NFTsinDrop = [
  {
    name: "SMB Barrel Raffle Over $30M!",
    rarity: "common",
    image: "https://arweave.net/PXYfbGaceOvi2trKeadNzJc5I25veYt8-yrIpaHauOc?ext=jpg",
    uri: "https://arweave.net/q7d5b1hsIVF-MC_vfDAakNsINysDPtj4AC0YNZuZoEk",
    magicEdenLink: "https://www.tensor.trade/trade/drip_floor",
    news: [
      { value: "$41.6M", trait_type: "Solana NFT Sales Volume" },
      { value: "256,000", trait_type: "Solana NFT # of Sales" },
      { value: "65,000", trait_type: "Solana NFT # of Buyers" },
      { value: "$19.80", trait_type: "Price of SOL" },
      { value: "SMB Gen 3 Barrel Raffle Receives Over $30M", trait_type: "Headline 1" },
      { value: "Solana 24 Hour NFT Sales Volume Breaks $20M", trait_type: "Headline 2" },
      { value: "Phantom Gets a New Ghost", trait_type: "Headline 3" },
      { value: "SMB Barrel", trait_type: "Highest Volume 1" },
      { value: "BoDoggos", trait_type: "Highest Volume 2" },
      { value: "Mad Lads", trait_type: "Highest Volume 3" },
    ],
  },
  {
    name: "Lets Get Down to Monkey Business",
    rarity: "legendary",
    image: "https://arweave.net/_MAo00nvVbhO7LKEoSA9JjEJingsPBzlnMeQseColaA?ext=jpg",
    uri: "https://arweave.net/IrDQN-jeLODxY25814AMslpoVfXW1IyM7jFj2DkgR10",
    magicEdenLink: "https://www.tensor.trade/trade/drip_floor",
    news: [
      { value: "$41.6M", trait_type: "Solana NFT Sales Volume" },
      { value: "256,000", trait_type: "Solana NFT # of Sales" },
      { value: "65,000", trait_type: "Solana NFT # of Buyers" },
      { value: "$19.80", trait_type: "Price of SOL" },
      { value: "SMB Gen 3 Barrel Raffle Receives Over $30M", trait_type: "Headline 1" },
      { value: "Solana 24 Hour NFT Sales Volume Breaks $20M", trait_type: "Headline 2" },
      { value: "Phantom Gets a New Ghost", trait_type: "Headline 3" },
      { value: "SMB Barrel", trait_type: "Highest Volume 1" },
      { value: "BoDoggos", trait_type: "Highest Volume 2" },
      { value: "Mad Lads", trait_type: "Highest Volume 3" },
    ],
  },
];
