export const NFTsinDrop = [
  {
    name: "Barbie Puffer",
    uri: "https://arweave.net/RP_Bgp67TFxjW5KYioxiRIdbIUYnsFke4KcS4o4Q9mM",
    rarity: "Common",
    image: "https://arweave.net/mjW97KBEf5LvJe_g0KqijOHdsFYpAbeYAPCIVA-yw64?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Black Puffer",
    uri: "https://arweave.net/vi9yLVDgpViatALgRsgA3c0t-ho9nwxJ8rG0wFJ0fZ8",
    rarity: "Common",
    image: "https://arweave.net/vIRb6RD0Q5oMh9GFOElP1b-0xcY_EjvBRt77KNc5eE0?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Brown Puffer",
    uri: "https://arweave.net/ZoTZAu7iUgQkZPC6jZS7fpqaZC_xYTDFc0e6qpi5_II",
    rarity: "Common",
    image: "https://arweave.net/Vs27VJgP6FR3DyergLl5a7oUz-RfUURJ5M8AYdrnATk?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Ceramic Blue Puffer",
    uri: "https://arweave.net/Sid49fqBP5e6iR28DDEyV_AoazKw7CXMLn82PFkrcyk",
    rarity: "Common",
    image: "https://arweave.net/9yagN9bwe_UU8UfIsmN9qUNhCOYVk_Eo8JMGKdLvIF0?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Denim Seams Puffer",
    uri: "https://arweave.net/Ozgw0h8P6iDsQVvKL9lrZNhjY9fz_9f6ToSrYFh0k3Q",
    rarity: "Common",
    image: "https://arweave.net/FGvBYIbYs8F857geYB2aUB-w0xjYDmiDgLLVY2MxNTo?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Fire Camo Puffer",
    uri: "https://arweave.net/ga3Fl50yAHyfNsyJlEq6N_fXpHgWT2Zx-d_Qg48Lx38",
    rarity: "Common",
    image: "https://arweave.net/_GWwWEL3F9GhiLs-y3VEQ5Ss0BFIvM42mDMA-rmSgsw?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Ghost Puffer",
    uri: "https://arweave.net/YkQej9Q2T1WSNAjXM7R091sqHlPi9ycyE5rUPkdU5HU",
    rarity: "Common",
    image: "https://arweave.net/HiLRmvD77xCEUKcGOP8f_cJNy1DeaS6-U8YPp51Uh6A?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Gold Puffer",
    uri: "https://arweave.net/3CbQbiRPl0uBn-3zWny9pOz3Ka92sFmbXcYgZhytneI",
    rarity: "Common",
    image: "https://arweave.net/-DeHb5VrfcumpN4-eX2Mo7jL3s14wK_tTIBgeQJZ0hc?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Green Puffer",
    uri: "https://arweave.net/QZYY35269xzRmhCJRENYjZSb9tOPeWE-cuKttYy5Ht4",
    rarity: "Common",
    image: "https://arweave.net/tRE_jIobDp2Szf2OTeGgB3BShouRefEx_SfmteFVcKQ?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Green Glow Puffer",
    uri: "https://arweave.net/CN5YsZYBX7swDef3nL1j5jQDhp7EFbi4XXA-TCrUPcY",
    rarity: "Common",
    image: "https://arweave.net/fztcOoHqK1ruph0iCv944cy9jA02CEA70wBtA3I5F_8?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Liquid Paint Puffer",
    uri: "https://arweave.net/-C_U9_kh7axfcuMNnBJqY-ZZ6uJwKVUuVaOD2ZZ6k7M",
    rarity: "Common",
    image: "https://arweave.net/9vfmPXQ8q7CWdpEINS1RCnN1Xn8tjTn5p_bPULWHCWw?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Mercurial Puffer",
    uri: "https://arweave.net/fWIoUPJD1k2-h1kIc5rzka5SvKhSjvjEQP481qs27zQ",
    rarity: "Common",
    image: "https://arweave.net/YIWbsSJ2jal9JV_1Jgpr3s7HOisVCRrcXCZ9u7m-iUo?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Military Camo Puffer",
    uri: "https://arweave.net/K_YkefUMvNy1k31DKkIi5JUkABJNFouhaxW_kBUPQbk",
    rarity: "Common",
    image: "https://arweave.net/wieacD9vqHUQG3i9M7BclMB0c-Ay0Gi1MMdF_IYWodc?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Nylon Puffer",
    uri: "https://arweave.net/thghnYahf3tK3aWdxM8GONxHLSpG1MgnHpknHssRwho",
    rarity: "Common",
    image: "https://arweave.net/5LDYExhlHDo2wrDLGDz2lAI8ofl5e0YJUk2_lWOYr7s?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Orange Puffer",
    uri: "https://arweave.net/zm49qKXcHBs3G2stXGhtbHSjML85pf6zMrm7nxGR2D4",
    rarity: "Common",
    image: "https://arweave.net/4qlBbRO78n9q-ma8EjAB1FyndbGX3wPNZDHhwgXqTnw?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Paint Splatter Puffer",
    uri: "https://arweave.net/rs41ZCF14p4FNnqpOfGX5Ic-XarjakeW_obPrExCByo",
    rarity: "Common",
    image: "https://arweave.net/Ul8iqpbY_3dR96hxOhq3POQ5Obfs-WaNAT1rKk-uyE0?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Plastic Puffer",
    uri: "https://arweave.net/bnM_RU8FpilIcTAkuaMBd_y6Uaai-kpoqP-yXlfVhOs",
    rarity: "Common",
    image: "https://arweave.net/KLSDviSrsYUiiS3V10FOPUqpEYpr9wz3rTyrsXM1E-w?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Polka Puffer",
    uri: "https://arweave.net/Wo0V5ONDxCai6MoPPHLzwwVIkMvajRl8peZyGJcb9xs",
    rarity: "Common",
    image: "https://arweave.net/B5VzAaIuFMnLPl61C3v0YHRA87GK6FHN4h-_Q-Mtqro?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Purple Camo Puffer",
    uri: "https://arweave.net/3aflPD-iSQYd3VY3-P_QaA692vqBn72K4FUvZQU9UtA",
    rarity: "Common",
    image: "https://arweave.net/wH1qC6n0f1g2pXtE07xD_BQrAqJfOQ5MARmuEu8mFR8?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Purple Latex Puffer",
    uri: "https://arweave.net/koWp5p1lsJj-_axO3Hu0_iqz88pnHEbAjPcduOhYkjY",
    rarity: "Common",
    image: "https://arweave.net/E2Se0d3-UvSZjDYTTedxvkMSUMdcIMAb-DU3YmM3nyI?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Red Puffer",
    uri: "https://arweave.net/GXUbpJ5sZiyOgmsRkKxmQ8ILzi0_QuREUF3wmIrBgAk",
    rarity: "Common",
    image: "https://arweave.net/FSyTIOnVzh87FQgHkdmujURzvOjOsw4GV2f69ovDGMU?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Rose Gold Puffer",
    uri: "https://arweave.net/Fyni7HC0k7u8qBXMBqAuYychHQH_jAtdDLr9qQteyAQ",
    rarity: "Common",
    image: "https://arweave.net/2U6aHcHE3OxtppcGxop6heR59ycBDoJ0Mf73lDNh61U?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Rusty Metal Puffer",
    uri: "https://arweave.net/grsRIPT13bAkYkwAgDOgxldxPxt7G1-tT7GWz159S0Y",
    rarity: "Common",
    image: "https://arweave.net/miFFQoVWiDY05_rygxpTM1W7MJC7TpIVaH_U6OWYqDw?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Smiley Puffer",
    uri: "https://arweave.net/XIWGe3lOPIfQH6YWKTPoYFF-JobceIPT9PBJMzzq87M",
    rarity: "Common",
    image: "https://arweave.net/obV71zd9uieRz0-dFMwg9zCmYot5h9ZT2fVYA5dlI0E?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Two-Tone Puffer",
    uri: "https://arweave.net/n3OYt1Ms2_x4uRIun6BdlQMWRAlR-RKGDi1nU2o7fSU",
    rarity: "Common",
    image: "https://arweave.net/2rvdE7B60msIp72KjyaaqsxIbLn5mzLQtnU-yTjLvUs?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Wavy Puffer",
    uri: "https://arweave.net/6N2tq8xswu24QNoXGjHxdyuiiJ7zxdcfeO1gT4yk6no",
    rarity: "Common",
    image: "https://arweave.net/nTNbiswSpsbsT9KKIuwIK8QuLZZzhaDmBSqo3CMmEiQ?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Wool Puffer",
    uri: "https://arweave.net/1kNv8ctmFQl2u-kUuG_Ub44skq8C_WvnLgEDvBN1llc",
    rarity: "Common",
    image: "https://arweave.net/Q9Psbp4O6D3PZ7kfhlG94t3ihh_nylTHndJ9GUxicOg?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
];
