export const NFTsinDrop = [
  {
    name: "NFT Addict",
    uri: "https://arweave.net/VCHU3xV09LpFl0-HsgkGTSwYU7X_pQCslSMp8Fgv37w",
    rarity: "Common",
    image: "https://arweave.net/eLtE3NT0czRGXSCf0ab2395_Rd8PU0xVgOq8PQAzfJw?ext=PNG",
    magicEdenLink: "https://www.tensor.trade/trade/drip_bangerz_origins",
  },
  {
    name: "Diamond Hands",
    uri: "https://arweave.net/FD6TaRVZvfuW5J8vRMLlCYzJitt7LQUsjeu0Goj6alQ",
    rarity: "Common",
    image: "https://arweave.net/v54VMnhDYJu16wUOk-B52SDZGqadlFciNXyLHFyxAdM?ext=PNG",
    magicEdenLink: "https://www.tensor.trade/trade/drip_bangerz_origins",
  },
  {
    name: "Sus",
    uri: "https://arweave.net/LxvbuucfELA3kTVG3Wode8LAzjoGSn5NYFWObFn1d5Y",
    rarity: "Common",
    image: "https://arweave.net/wGxlSZ9MiMEqspZSuj_j_4Tc1Id1yi3pPNwp6205nsg?ext=PNG",
    magicEdenLink: "https://www.tensor.trade/trade/drip_bangerz_origins",
  },
  {
    name: "Memes are Art",
    uri: "https://arweave.net/A9Sr2HCbVPr3TFD7udLIZns44sy02gKxDUjG2OzCs7s",
    rarity: "Common",
    image: "https://arweave.net/n7f_tixnZQpDy0-pTNNT1-Zyv0dHuEMHDE3lP2JOILA?ext=PNG",
    magicEdenLink: "https://www.tensor.trade/trade/drip_bangerz_origins",
  },
  {
    name: "Instagram Sucks",
    uri: "https://arweave.net/3v-hiE0v4YVjmN9y22CMPiswpqQf_m7LkN803Tjbo3o",
    rarity: "Common",
    image: "https://arweave.net/fIHTi4T4bn9JbnJm1DybaT-ylCqfebR41R66WzxrXQk?ext=PNG",
    magicEdenLink: "https://www.tensor.trade/trade/drip_bangerz_origins",
  },
  {
    name: "Death To Web2",
    uri: "https://arweave.net/1tK_AtV4SDMkPhjLrLdlDu_aSdp_yxt9BLjjKyfkzF4",
    rarity: "Common",
    image: "https://arweave.net/qxC-znaJMuRWxXp0Ctq6yt2OPfaZXjm7jG1quXkSGok?ext=PNG",
    magicEdenLink: "https://www.tensor.trade/trade/drip_bangerz_origins",
  },
  {
    name: "Engagement",
    uri: "https://arweave.net/UyiyDX_TN5gIAcdIr6LNL2WC11zCQpX2Bhj7w-WrobY",
    rarity: "Rare",
    image: "https://arweave.net/P9WFmnMVb03TJY9mpNhPrammrPpgrz7RSt5Vn11MifE?ext=PNG",
    magicEdenLink: "https://www.tensor.trade/trade/drip_bangerz_origins",
  },
  {
    name: "Cheers",
    uri: "https://arweave.net/HsdgGeQ8ii48YFyk4R0Xd_0t4N7ptPxnq5--EUyoy0g",
    rarity: "Rare",
    image: "https://arweave.net/_rEpPYxRK2DzzZ2oZBhBg6QNJk0r19Cz3xllLF3bAQY?ext=PNG",
    magicEdenLink: "https://www.tensor.trade/trade/drip_bangerz_origins",
  },
  {
    name: "Barf",
    uri: "https://arweave.net/qjLIPmkauPCcv76B5wUvxdRc6mreCiCkxKo5KvhP2_4",
    rarity: "Rare",
    image: "https://arweave.net/V6GSqKJsBlvF7ALGehqIvyPE3Frp4a4_V3Wc1N2zoc4?ext=PNG",
    magicEdenLink: "https://www.tensor.trade/trade/drip_bangerz_origins",
  },
  {
    name: "Pink Devil Pepe",
    uri: "https://arweave.net/Y99edz1wixwJkM76fOmje1NePNWzzt3OSPmlPwraL4Q",
    rarity: "Legendary",
    image: "https://arweave.net/ys01kAHra023PJwudyH9K6qc1H1DTQ654QJtHpjohIc?ext=PNG",
    magicEdenLink: "https://www.tensor.trade/trade/drip_bangerz_origins",
  },
];
