export const NFTsinDrop = [
  {
    name: "Literally Rugged Yourself",
    uri: "https://arweave.net/wzw3hs4yh-B1I1Ob524ITFCRL4H2bLvTMnSnXz3qxgM",
    rarity: "Common",
    image: "https://arweave.net/JjfQzVhbwgzibcfurkROWerutQhMAqXlcZ0Nojr-ruU?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Shoulda Read The Rules",
    uri: "https://arweave.net/r743xoXpLM2KiskJltj-9q0iYp2S_4-h0fgq39cKcw4",
    rarity: "Common",
    image: "https://arweave.net/HUdW29YYuII7TprjHT0hW6jbGLCmTSV3PLp3cT29hBw?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Where's My Two:One?",
    uri: "https://arweave.net/GyLNQGkBD-Zm_ZgZh6dLzACVbiGHLHkjCOeHnTedneM",
    rarity: "Common",
    image: "https://arweave.net/Xtil9JeSmkQdgCH0oLD24FwCBoa_IDs-WyZ6MFIb7p8?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Barbie Sneaker",
    uri: "https://arweave.net/LbYdZnuF5w2ZZxA1NarEZa9lr86BQHbKH8Zk0jDwdT0",
    rarity: "Rare",
    image: "https://arweave.net/SJ-goPnvm9NeKH7b3bgv_CLx3VjHGyjSW_ImgJcnMso?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Black Sneaker",
    uri: "https://arweave.net/vjpwelSMrntRhMS7B33_0UMjxh3HmOc32UPpFDYioSY",
    rarity: "Rare",
    image: "https://arweave.net/k00rsgvIS-utZ-zPyVhXKbeu5OlN_TGsZOjiS7TfRUg?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Brown Sneaker",
    uri: "https://arweave.net/HM5ALPgVkjDg9I-1US3mDSDi0KEVYk4bqRInItZQDDI",
    rarity: "Rare",
    image: "https://arweave.net/cWY190XrQ6gbKQ7VfFhsgOVtRDrMGycDMOhqvjZtr2M?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Carbon Sneaker",
    uri: "https://arweave.net/GeDwUfuV-OvwyDFm4e_6jxPpwqqkE1a9FwC-RYVe16E",
    rarity: "Rare",
    image: "https://arweave.net/vL_GfJFEuo8hgaiDrM7ADJH1XGoUyqKErvRHbM99MoM?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Ceramic Blue Sneaker",
    uri: "https://arweave.net/O0kqwkZphur309MyAFs6HJKGv49-1Xx0SUX7_OiKAHY",
    rarity: "Rare",
    image: "https://arweave.net/xaOaW0Bl1VMJqxS9OkMmr20OWRQsvQmiNci-4DFTYDs?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Denim Seams Sneaker",
    uri: "https://arweave.net/klBTyv7KUEkOmmlbZtFwBUqZVNvhiZbpmTEvjyDh0_U",
    rarity: "Rare",
    image: "https://arweave.net/Y7vstSYioWIpFllZteMZTnAMbfEkUkEBccBf9tUvow8?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Fire Camo Sneaker",
    uri: "https://arweave.net/6Zjb9Wo5Vr-bWwo9RRU4klpIW2wN0H3exWsYXuVM9TM",
    rarity: "Rare",
    image: "https://arweave.net/TbDN5o7l-kQFjCm19mKObHeXlQlgFGt_efXa7sMU29I?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Gold Sneaker",
    uri: "https://arweave.net/cxHgWjwKZFmB--Xr67QlTtpdMr01qqJStfCdib0hS8w",
    rarity: "Rare",
    image: "https://arweave.net/flWd_norcy8mx0yBZ14rW0oM4bquHA715zfN5ufByvM?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Green Sneaker",
    uri: "https://arweave.net/7WXYLO63Aew6OMWriCM8rTlR6tmPgywO8yT1EzJTqZg",
    rarity: "Rare",
    image: "https://arweave.net/LgUInwWiHuXkOwsgmQUq1OcE6gustUARgu74JSTMEUs?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Green Glow Sneaker",
    uri: "https://arweave.net/gP9TeL7XansVBdX2clJvCPvp3Nmg_DW-enhvdTLZ3jg",
    rarity: "Rare",
    image: "https://arweave.net/FgRtCG9pNsmCA3GAns6Env4JMkD92rikQqMooI5FglU?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Invader Sneaker",
    uri: "https://arweave.net/W9cHuz8GpmV0LJ9AfBWpvJd2M5q85OEZrEZpOMCCkgc",
    rarity: "Rare",
    image: "https://arweave.net/1jN6nYtTmyaZp4jX6ETWA3tyx32AjsD_mdGomAV-n-k?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Liquid Paint Sneaker",
    uri: "https://arweave.net/urFdmNsWaNiZdA4WKVmpNotuZ_tBCl1-BhSdat56J-c",
    rarity: "Rare",
    image: "https://arweave.net/dnEEmaxJzA-rdpKd6ktlnfAwnJSG6ibp1P44Bvi-bFQ?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Mercurial Sneaker",
    uri: "https://arweave.net/hC2ON91-jFfCFeQIkZVolOqKVbI_Hg-HBqRVPzulx3Q",
    rarity: "Rare",
    image: "https://arweave.net/AdN4K3cHIXYCSVjo6TKEfkz6yYg9gjBxVYyKA_jbK80?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Metallic Purple Sneaker",
    uri: "https://arweave.net/YeJedoqOfAPm-5CCmrTNW3EEOCOVY8PRCVrQsQTpp18",
    rarity: "Rare",
    image: "https://arweave.net/GTJgUWoyzv5kSrHmf7Jf5Rpdi2i4vKojbij_dh6YW4k?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Military Camo Sneaker",
    uri: "https://arweave.net/zp0fOYyTRJPJwCU8r9hC0-ncoekvwlKk5MsBYtu1kwo",
    rarity: "Rare",
    image: "https://arweave.net/8MDcRzf-XjB5YpN93-seEFa1URJiDv2trf5-wP789nQ?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Milky Sneaker",
    uri: "https://arweave.net/JprcNlUnQ4rqHOO2YksNSBbTW_-5pOeQ0MOQ9SQE_go",
    rarity: "Rare",
    image: "https://arweave.net/lSsSxwock_wsLeuR0sqo9YBSy3gSfg0L3w8b2L5RCO8?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Nylon Sneaker",
    uri: "https://arweave.net/OGDmKbkexPsttt1Kk64cG65P0PVPhVrIS3-yQkIDTl4",
    rarity: "Rare",
    image: "https://arweave.net/D-WKrhAQ6ae75WZV4Nj9y8r_Lpjj2RENWcvGNKiEdko?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "October Sneaker",
    uri: "https://arweave.net/_Z1NoPThapTwR2sQ8YWYosiSIcWNzRoH4ezMYJj4QX0",
    rarity: "Rare",
    image: "https://arweave.net/fnd2j6UpaZMcewWYcYHuOTrwc455PFRpPR4ffT-0IcI?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Orange Sneaker",
    uri: "https://arweave.net/-ZDZGWI0D2b0x5M4R468xP6KzqW2J07QSnSFKvTG-jo",
    rarity: "Rare",
    image: "https://arweave.net/ttebCTTFZY3updNoPwyOvBIatSatMCSRrmimH1-O0x8?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Polka Sneaker",
    uri: "https://arweave.net/J2ZO8lFmwCCw8vsFzsK37FsDHo84fBHtOOkPz8F8xqQ",
    rarity: "Rare",
    image: "https://arweave.net/i5KqcjaC6SZTdv4vidupgHVBwMzomI55U2Gt2Q1so0c?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Purple Camo Sneaker",
    uri: "https://arweave.net/ILj_EYzF9qPdY2h4GWgDni4_WqnwKNYWV7kwGM4ma-Q",
    rarity: "Rare",
    image: "https://arweave.net/0RaMfSPqFHqULIYMTQRh272NVLCV1MviPjuMzOxSD5U?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Rose Gold Sneaker",
    uri: "https://arweave.net/vzpvc0mi6A-dqNsT6IYggtAUnTYp9rYwxFNJ4UT6-Hk",
    rarity: "Rare",
    image: "https://arweave.net/uxBoiOwxs4mz-iiD9bfc-grLEGcqhcJZjKjfht9VVug?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Rover Sneaker",
    uri: "https://arweave.net/cFJdjJkmdIfp-MzgwjYeqMWnijk1k4JVbM4AOK7AOIE",
    rarity: "Rare",
    image: "https://arweave.net/wEMdCvGCNqYFKpWtiuNI7qU-fChWRtexbxcY-gbJSLY?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Smiley Sneaker",
    uri: "https://arweave.net/Rw-te8P6G8VWnjlt5AM_vs4m7M4VNmlilU7CZZSVtxQ",
    rarity: "Rare",
    image: "https://arweave.net/Oe5eftDRYYCLXNEsIZNaiMWmpnNcKJ7yixEMP1WFUaI?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Tiffany Sneaker",
    uri: "https://arweave.net/CRXBtoh63Ukvjoq5NFIMl2F-OdUxHBkaTRJIOHqYXQQ",
    rarity: "Rare",
    image: "https://arweave.net/OjtgAEVfZ4HD5ktMOHTzCyTKKhj0_lu8E_YLXLEzNnU?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Two-Tone Sneaker",
    uri: "https://arweave.net/kfi_Hesj2BUKt-dYsJCWoKLLr_FGt_XXIrbqYNz4xt0",
    rarity: "Rare",
    image: "https://arweave.net/hEWxXo0e2NEs2lQyyY5AJHRbio97aoad4NvuHBD1tSc?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Wavy Sneaker",
    uri: "https://arweave.net/c38WCntKnLBGiQSLCzfkf7Hc04QAada2tJg6Pq77gv8",
    rarity: "Rare",
    image: "https://arweave.net/01i9C3jIkbDYWg43JEAMoNGgfY2xTNVo0-YUVCGLKV0?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
];
