export const NFTsinDrop = [
  {
    name: "Breaking: SEC Sues Coinbase",
    rarity: "Common",
    image: "https://arweave.net/Th5WutzqZLzzEW46eazvsOaMf7ElDgGKO9KCgmS6y50?ext=png",
    uri: "https://arweave.net/hKXJxtqIRSpFVr9zzHirrtUhdIjDAK0-7fqRzQB5C_k",
    magicEdenLink: "https://www.tensor.trade/trade/drip_floor",
    news: [
      { value: "$8.3M", trait_type: "Solana NFT Sales Volume" },
      { value: "118k", trait_type: "Solana NFT # of Sales" },
      { value: "14.6k", trait_type: "Solana NFT # of Buyers" },
      { value: "$14.94", trait_type: "Price of SOL" },
      { value: "SEC Sues Coinbase and Binance", trait_type: "Headline 1" },
      { value: "Apple Announces VR Headset Vision Pro", trait_type: "Headline 2" },
      { value: "Robinhood Delists $SOL", trait_type: "Headline 3" },
      { value: "Mad Lads", trait_type: "Highest Volume 1" },
      { value: "Zero Monke Biz", trait_type: "Highest Volume 2" },
      { value: "ABC", trait_type: "Highest Volume 3" },
    ],
  },
  {
    name: "Breaking: SEC Sues Coinbase",
    rarity: "Legendary",
    image: "https://arweave.net/EUOm0NRguHP_t--ApwBwMYg5alJa7YRhI8uNiJ8U-BY?ext=png",
    uri: "https://arweave.net/h9PAtZQ_-rionqPr2uF9OMDbD9aBK8vdCLjBPvh2M2Y",
    magicEdenLink: "https://www.tensor.trade/trade/drip_floor",
    news: [
      { value: "$8.3M", trait_type: "Solana NFT Sales Volume" },
      { value: "118k", trait_type: "Solana NFT # of Sales" },
      { value: "14.6k", trait_type: "Solana NFT # of Buyers" },
      { value: "$14.94", trait_type: "Price of SOL" },
      { value: "SEC Sues Coinbase and Binance", trait_type: "Headline 1" },
      { value: "Apple Announces VR Headset Vision Pro", trait_type: "Headline 2" },
      { value: "Robinhood Delists $SOL", trait_type: "Headline 3" },
      { value: "Mad Lads", trait_type: "Highest Volume 1" },
      { value: "Zero Monke Biz", trait_type: "Highest Volume 2" },
      { value: "ABC", trait_type: "Highest Volume 3" },
    ],
  },
];
