export const NFTsinDrop = [
  {
    name: "No Drip",
    uri: "https://arweave.net/P-5qVdNGmt8cAi5J86CV51b4GKgNWJ27MvPLT7UdMjw",
    rarity: "Common",
    image: "https://arweave.net/BrEv6FwMo6xuZc5xyuiUk4tmKat1evBUQKngeUMQ3Nc?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Barbie Cargo Shorts",
    uri: "https://arweave.net/u11XR7N8tHp7gmUfdwvt_oQet0gQis-ttSFEiUccTRg",
    rarity: "Rare",
    image: "https://arweave.net/cdX8mDV0XyGX5KTuCgmFtAqBVQBxf77Sygi0cGBVKkI?e=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Black Cargo Shorts",
    uri: "https://arweave.net/ZcN2ezEC_ZA61SAmR_qa8jm5eofF5cfVW4y84L66EOA",
    rarity: "Rare",
    image: "https://arweave.net/bp8JJfSqb0pcuwldAygsI6SVBjaf7N9OYPhkt8ka8YE?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Carbon Cargo Shorts",
    uri: "https://arweave.net/ZwMv_0YDB7VU1H6U_NNaVQm_bhbyPGLk8uJcE_VrpHc",
    rarity: "Rare",
    image: "https://arweave.net/4cNhrlHd21JrMCWRqjLKL-qLwbL6aEzG_4SL4SD3ZbQ?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Ghost Cargo Shorts",
    uri: "https://arweave.net/5Kv-KELwqx2jg2ul27zfqkcwNd-ZOfiQY0ZIFjxTCWY",
    rarity: "Rare",
    image: "https://arweave.net/5N1Vw0sXqi5nfeFktY4pNmbM4lGlx-FTwuW7WWS63vI?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Gold Cargo Shorts",
    uri: "https://arweave.net/aqnMgPpTjzF8w5w5HZVGMMFLSpUC9IEFA7TvlTBPXKk",
    rarity: "Rare",
    image: "https://arweave.net/aiEBhKSItPbys7P-57wQs_mJp4GEVaB4LnB6343XH7w?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Green Glow Cargo Shorts",
    uri: "https://arweave.net/QhjmdzuVncr05nv5uyrh_0ogr4j3ytqc_N_8Bonvpmg",
    rarity: "Rare",
    image: "https://arweave.net/ioRXqxfVBuAIUWkH0CgrFNgGh8M8IoxP1tckRMeQtYw?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Liquid Paint Cargo Shorts",
    uri: "https://arweave.net/lAjFY9wfZXs10nHwTu7GszJyhC6tZDgpL2IkLz6nS5w",
    rarity: "Rare",
    image: "https://arweave.net/-qCIJbT38p04UjLpCovhesmN1iYuomavx50V08QRW7Y?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Milky Cargo Shorts",
    uri: "https://arweave.net/DyQqDBHFKZxdZOMtC7g4Nw3xdIDXuAC5R-QcMpY1YzY",
    rarity: "Rare",
    image: "https://arweave.net/ZuVVhzaLoUXXArkp5Jqott9UmLiMz88gtLr40GqpinM?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Purple Cargo Shorts",
    uri: "https://arweave.net/qUWvJeQzdhFc8icrIpW-ki2LWPd_qVNP-0dUkOTrqqw",
    rarity: "Rare",
    image: "https://arweave.net/mjAM0oBYNZ8cHm-DAY2GQpe5VZnA_DF21NZzEISHzvQ?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Purple Camo Cargo Shorts",
    uri: "https://arweave.net/_f2BvCL76LzBGSsIqWYLVKyq3O9A6MTpw0-1xpcjzHM",
    rarity: "Rare",
    image: "https://arweave.net/f_9s9oyjOXiT3x20IjYkaaa_-JCgFvOwWP8X2Cub2OU?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Wavy Cargo Shorts",
    uri: "https://arweave.net/k6BGfCcwR5M97vqyDi9T7AEvymMa3YC7FRUWcLPJ1OU",
    rarity: "Rare",
    image: "https://arweave.net/7Irz4Mdcyex5UMU1qR-dLN6ZVH1wFQ3hot6gAth3u_g?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
  {
    name: "Wool Cargo Shorts",
    uri: "https://arweave.net/58g_GW9uxzaKO292BBGYESJ0dMTlowUTv9CUXj_viSY",
    rarity: "Rare",
    image: "https://arweave.net/hF2B-SgH-y-7T9C6e42RHlxij8FWBn-ofXLyRSD_t68?ext=png",
    magicEdenLink: "https://www.tensor.trade/trade/drip_silicons_season_1",
  },
];
